"""
Company registry for JobMatch AI — Pakistan edition.

Two datasets:

1. ATS_BOARDS — companies with (possible) public ATS boards we can pull live
   jobs from (Greenhouse, Lever, Ashby, Workable, SmartRecruiters, Recruitee,
   BambooHR, Breezy). Slugs are best-effort seeds: the app VERIFIES each board
   at runtime (/api/sources/verify) and remembers which ones resolve, so a dead
   or renamed slug degrades gracefully instead of "blocking" everything.
   Add your own in data/custom_boards.json — same shape, merged on startup.

2. PK_DIRECTORY — a large curated directory of real Pakistani employers
   (name, sector, city, website-domain-or-empty). Used for the Company
   Directory tab: search, filter by sector/city, jump to careers via a
   guaranteed search link (and website when known). No fabricated entries.
"""

# ---------------------------------------------------------------------------
# 1) LIVE ATS BOARDS  (name, ats, slug, pk_relevant, tags)
#     ats ∈ greenhouse | lever | ashby | workable | smartrecruiters |
#           recruitee | bamboohr | breezy
#     pk_relevant=True → offices in Pakistan or a track record of hiring
#     Pakistan-based/remote talent. Slugs are unverified seeds by design.
# ---------------------------------------------------------------------------

ATS_BOARDS = [
    # --- Pakistan offices / PK-founded ---
    ("Motive",                "greenhouse",      "gomotive",          True,  ["devops", "backend", "ai"]),
    ("Careem",                "greenhouse",      "careem",            True,  ["backend", "mobile", "data"]),
    ("Afiniti",               "greenhouse",      "afiniti",           True,  ["ai", "data", "backend"]),
    ("Turing",                "greenhouse",      "turing",            True,  ["remote", "ai", "fullstack"]),
    ("Educative",             "lever",           "educative",         True,  ["fullstack", "content", "backend"]),
    ("Securiti",              "lever",           "securiti",          True,  ["security", "backend", "ai"]),
    ("Bazaar Technologies",   "lever",           "bazaartechnologies",True,  ["backend", "data", "product"]),
    ("Dubizzle Labs",         "lever",           "dubizzlelabs",      True,  ["backend", "frontend", "data"]),
    ("Tajir",                 "lever",           "tajir",             True,  ["backend", "ops"]),
    ("Retailo",               "lever",           "retailo",           True,  ["backend", "data"]),
    ("Bykea",                 "lever",           "bykea",             True,  ["mobile", "backend"]),
    ("Remotebase",            "lever",           "remotebase",        True,  ["remote", "fullstack"]),
    ("SadaPay",               "workable",        "sadapay",           True,  ["fintech", "mobile", "backend"]),
    ("NayaPay",               "workable",        "nayapay",           True,  ["fintech", "backend"]),
    ("Abhi",                  "workable",        "abhi",              True,  ["fintech", "backend"]),
    ("CreditBook",            "workable",        "creditbook",        True,  ["fintech", "mobile"]),
    ("Neem",                  "workable",        "neem",              True,  ["fintech", "backend"]),
    ("PostEx",                "workable",        "postex",            True,  ["logistics", "backend"]),
    ("Gaditek",               "workable",        "gaditek",           True,  ["devops", "fullstack", "security"]),
    ("VentureDive",           "workable",        "venturedive",       True,  ["fullstack", "mobile", "qa"]),
    ("PriceOye",              "workable",        "priceoye",          True,  ["ecommerce", "backend"]),
    ("GrocerApp",             "workable",        "grocerapp",         True,  ["ecommerce", "backend"]),
    ("Krave Mart",            "lever",           "kravemart",         True,  ["ecommerce", "backend"]),
    ("Dastgyr",               "workable",        "dastgyr",           True,  ["ecommerce", "backend"]),
    ("Zameen",                "workable",        "zameen",            True,  ["frontend", "backend", "data"]),
    ("Daraz",                 "recruitee",       "daraz",             True,  ["ecommerce", "data", "backend"]),
    ("Foodpanda (Delivery Hero)", "smartrecruiters", "DeliveryHero",  True,  ["ecommerce", "data", "backend"]),
    ("Jazz (VEON)",           "smartrecruiters", "VEON",              True,  ["telecom", "data", "devops"]),
    ("Systems Limited",       "smartrecruiters", "SystemsLimited",    True,  ["enterprise", "fullstack"]),
    ("10Pearls",              "greenhouse",      "10pearls",          True,  ["fullstack", "mobile", "qa"]),
    ("Arbisoft",              "bamboohr",        "arbisoft",          True,  ["python", "fullstack", "data"]),
    ("Tkxel",                 "workable",        "tkxel",             True,  ["fullstack", "mobile"]),
    ("Confiz",                "workable",        "confiz",            True,  ["data", "dotnet", "retail-tech"]),
    ("Devsinc",               "workable",        "devsinc",           True,  ["fullstack", "ruby", "python"]),
    ("Folio3",                "workable",        "folio3",            True,  ["fullstack", "ai", "erp"]),
    ("NetSol Technologies",   "workable",        "netsol",            True,  ["enterprise", "fintech"]),
    ("Contour Software",      "bamboohr",        "contour",           True,  ["dotnet", "fullstack"]),
    ("InvoZone",              "workable",        "invozone",          True,  ["fullstack", "python"]),
    ("Emumba",                "workable",        "emumba",            True,  ["data", "devops", "python"]),
    ("Qbatch",                "workable",        "qbatch",            True,  ["fullstack", "python"]),
    ("Xavor",                 "workable",        "xavor",             True,  ["ai", "fullstack"]),
    ("NorthBay Solutions",    "workable",        "northbaysolutions", True,  ["aws", "data", "ml"]),
    ("Xgrid",                 "workable",        "xgrid",             True,  ["devops", "cloud", "frontend"]),
    ("Wanclouds",             "workable",        "wanclouds",         True,  ["cloud", "devops"]),
    ("CareCloud",             "workable",        "carecloud",         True,  ["healthtech", "fullstack"]),
    ("i2c Inc",               "workable",        "i2cinc",            True,  ["fintech", "backend"]),
    ("Shufti Pro",            "workable",        "shuftipro",         True,  ["ai", "kyc", "backend"]),
    ("Tintash",               "bamboohr",        "tintash",           True,  ["games", "mobile", "fullstack"]),
    ("Mindstorm Studios",     "workable",        "mindstormstudios",  True,  ["games", "unity"]),
    ("Game District",         "workable",        "gamedistrict",      True,  ["games", "unity"]),
    ("Cubix",                 "workable",        "cubix",             True,  ["mobile", "fullstack", "blockchain"]),
    ("Ebryx",                 "workable",        "ebryx",             True,  ["security", "backend"]),
    ("Rewterz",               "workable",        "rewterz",           True,  ["security", "soc"]),
    ("Vyro AI",               "workable",        "vyro",              True,  ["ai", "mobile"]),
    ("Sastaticket",           "workable",        "sastaticket",       True,  ["travel", "backend"]),
    ("Bookme",                "workable",        "bookme",            True,  ["travel", "backend"]),
    ("oladoc",                "workable",        "oladoc",            True,  ["healthtech", "fullstack"]),
    ("Marham",                "workable",        "marham",            True,  ["healthtech", "fullstack"]),
    ("Sehat Kahani",          "workable",        "sehatkahani",       True,  ["healthtech"]),
    ("Dawaai",                "workable",        "dawaai",            True,  ["healthtech", "ecommerce"]),
    ("XStak",                 "workable",        "xstak",             True,  ["ecommerce", "backend"]),
    ("Salesflo",              "workable",        "salesflo",          True,  ["saas", "backend"]),
    ("Walee",                 "workable",        "walee",             True,  ["martech", "data"]),
    ("Addo AI",               "workable",        "addoai",            True,  ["ai", "data"]),
    ("Love For Data",         "workable",        "lovefordata",       True,  ["data", "ml"]),
    ("Xeven Solutions",       "workable",        "xevensolutions",    True,  ["ai", "fullstack"]),
    ("Carbonteq",             "workable",        "carbonteq",         True,  ["fullstack", "node"]),
    ("GigaLabs",              "workable",        "gigalabs",          True,  ["fullstack"]),
    ("Truck It In",           "lever",           "truckitin",         True,  ["logistics", "backend"]),
    ("Bridgelinx",            "lever",           "bridgelinx",        True,  ["logistics", "backend"]),
    ("Jugnu",                 "workable",        "jugnu",             True,  ["ecommerce", "backend"]),
    ("Markaz",                "workable",        "markaz",            True,  ["ecommerce", "mobile"]),
    ("Laam",                  "workable",        "laam",              True,  ["ecommerce", "frontend"]),
    ("Finja",                 "workable",        "finja",             True,  ["fintech", "backend"]),
    ("Oraan",                 "workable",        "oraan",             True,  ["fintech"]),
    ("Safepay",               "workable",        "safepay",           True,  ["fintech", "backend"]),
    ("Paymob",                "workable",        "paymob",            True,  ["fintech", "backend"]),
    ("Haball",                "workable",        "haball",            True,  ["fintech", "b2b"]),
    ("Zaraye",                "workable",        "zaraye",            True,  ["b2b", "backend"]),
    ("DealCart",              "workable",        "dealcart",          True,  ["ecommerce"]),
    ("Maqsad",                "workable",        "maqsad",            True,  ["edtech", "mobile"]),
    ("Abwaab",                "workable",        "abwaab",            True,  ["edtech"]),
    ("Knowledge Platform",    "workable",        "knowledgeplatform", True,  ["edtech", "fullstack"]),
    ("Out-Class",             "workable",        "outclass",          True,  ["edtech"]),
    ("Ciklum",                "workable",        "ciklum",            True,  ["fullstack", "enterprise"]),
    ("Royal Cyber",           "workable",        "royalcyber",        True,  ["enterprise", "cloud"]),
    ("Kualitatem",            "workable",        "kualitatem",        True,  ["qa", "security"]),

    # --- Global, remote-friendly, known to hire across Asia/worldwide ---
    ("GitLab",                "greenhouse",      "gitlab",            False, ["remote", "devops", "ruby"]),
    ("Canonical",             "greenhouse",      "canonical",         False, ["remote", "linux", "python"]),
    ("Zapier",                "greenhouse",      "zapier",            False, ["remote", "python", "frontend"]),
    ("DuckDuckGo",            "greenhouse",      "duckduckgo",        False, ["remote", "backend"]),
    ("Vercel",                "greenhouse",      "vercel",            False, ["remote", "frontend", "infra"]),
    ("Remote.com",            "greenhouse",      "remotecom",         False, ["remote", "fullstack"]),
    ("Andela",                "greenhouse",      "andela",            False, ["remote", "fullstack"]),
    ("Wikimedia Foundation",  "greenhouse",      "wikimedia",         False, ["remote", "backend", "sre"]),
    ("Mozilla",               "greenhouse",      "mozilla",           False, ["remote", "backend", "rust"]),
    ("Elastic",               "greenhouse",      "elastic",           False, ["remote", "search", "devops"]),
    ("Grafana Labs",          "greenhouse",      "grafanalabs",       False, ["remote", "observability", "go"]),
    ("Kraken",                "lever",           "kraken",            False, ["remote", "crypto", "backend"]),
    ("Deel",                  "ashby",           "deel",              False, ["remote", "fullstack"]),
    ("Supabase",              "ashby",           "supabase",          False, ["remote", "postgres", "infra"]),
    ("PostHog",               "ashby",           "posthog",          False, ["remote", "product", "fullstack"]),
    ("Hotjar",                "workable",        "hotjar",            False, ["remote", "frontend", "data"]),
    ("Binance",               "lever",           "binance",           False, ["remote", "crypto", "backend"]),
    ("Chainlink Labs",        "lever",           "chainlink",         False, ["remote", "blockchain"]),
    ("Automattic",            "greenhouse",      "automattic",        False, ["remote", "php", "fullstack"]),
    ("Toggl",                 "workable",        "toggl",             False, ["remote", "backend"]),
]

# ---------------------------------------------------------------------------
# 2) PAKISTAN EMPLOYER DIRECTORY  (name, sector, city, website-domain or "")
#     Real companies only. Website left blank when not confidently known —
#     the UI always provides a guaranteed careers-search link regardless.
# ---------------------------------------------------------------------------

PK_DIRECTORY = [
    # ---- Software & IT services ----
    ("Systems Limited", "Software & IT services", "Lahore", "systemsltd.com"),
    ("NetSol Technologies", "Software & IT services", "Lahore", "netsoltech.com"),
    ("10Pearls", "Software & IT services", "Karachi", "10pearls.com"),
    ("Arbisoft", "Software & IT services", "Lahore", "arbisoft.com"),
    ("VentureDive", "Software & IT services", "Karachi", "venturedive.com"),
    ("Techlogix", "Software & IT services", "Lahore", "techlogix.com"),
    ("Contour Software", "Software & IT services", "Karachi", "contour-software.com"),
    ("Folio3", "Software & IT services", "Karachi", "folio3.com"),
    ("Devsinc", "Software & IT services", "Lahore", "devsinc.com"),
    ("Nextbridge", "Software & IT services", "Lahore", "nextbridge.com"),
    ("Tkxel", "Software & IT services", "Lahore", "tkxel.com"),
    ("Confiz", "Software & IT services", "Lahore", "confiz.com"),
    ("Cubix", "Software & IT services", "Karachi", "cubix.co"),
    ("PureLogics", "Software & IT services", "Lahore", "purelogics.com"),
    ("Genetech Solutions", "Software & IT services", "Karachi", "genetechsolutions.com"),
    ("Strategic Systems International", "Software & IT services", "Lahore", "ssidecisions.com"),
    ("Xavor", "Software & IT services", "Lahore", "xavor.com"),
    ("ArhamSoft", "Software & IT services", "Lahore", "arhamsoft.com"),
    ("InvoZone", "Software & IT services", "Lahore", "invozone.com"),
    ("Emumba", "Software & IT services", "Islamabad", "emumba.com"),
    ("Qbatch", "Software & IT services", "Lahore", "qbatch.com"),
    ("Ropstam Solutions", "Software & IT services", "Islamabad", "ropstam.com"),
    ("Codup", "Software & IT services", "Karachi", "codup.co"),
    ("KoderLabs", "Software & IT services", "Karachi", "koderlabs.com"),
    ("Vaival Technologies", "Software & IT services", "Lahore", "vaival.com"),
    ("Five Rivers Technologies", "Software & IT services", "Lahore", "fiverivers.com"),
    ("Sofizar / ConstellationCK", "Software & IT services", "Lahore", ""),
    ("Bramerz", "Software & IT services", "Lahore", "bramerz.com"),
    ("Symmetry Group", "Software & IT services", "Karachi", "symmetrygroup.biz"),
    ("Creative Chaos", "Software & IT services", "Karachi", "creativechaos.co"),
    ("Conrad Labs", "Software & IT services", "Lahore", "conradlabs.com"),
    ("Arpatech", "Software & IT services", "Karachi", "arpatech.com"),
    ("NorthBay Solutions", "Software & IT services", "Lahore", "northbaysolutions.com"),
    ("Xgrid", "Software & IT services", "Islamabad", "xgrid.co"),
    ("Teresol", "Software & IT services", "Rawalpindi", "teresol.com"),
    ("Alachisoft", "Software & IT services", "Islamabad", "alachisoft.com"),
    ("Sybrid (Lakson Group)", "Software & IT services", "Karachi", "sybrid.com"),
    ("TPS Worldwide", "Software & IT services", "Karachi", "tpsworldwide.com"),
    ("Avanza Solutions", "Software & IT services", "Karachi", "avanzasolutions.com"),
    ("NdcTech", "Software & IT services", "Karachi", "ndctech.com"),
    ("Autosoft Dynamics", "Software & IT services", "Lahore", "autosoftdynamics.com"),
    ("Inbox Business Technologies", "Software & IT services", "Karachi", "inboxbiz.com"),
    ("Jaffer Business Systems", "Software & IT services", "Karachi", "jbs.live"),
    ("Abacus Consulting", "Software & IT services", "Lahore", "abacus-global.com"),
    ("LMKR", "Software & IT services", "Islamabad", "lmkr.com"),
    ("Ovex Technologies", "Software & IT services", "Islamabad", "ovextech.com"),
    ("DPL", "Software & IT services", "Islamabad", "dplit.com"),
    ("Zones Pakistan", "Software & IT services", "Islamabad", "zones.com"),
    ("Wanclouds", "Software & IT services", "Islamabad", "wanclouds.net"),
    ("CareCloud (MTBC)", "Software & IT services", "Rawalpindi", "carecloud.com"),
    ("i2c Inc", "Software & IT services", "Lahore", "i2cinc.com"),
    ("Gaditek", "Software & IT services", "Karachi", "gaditek.com"),
    ("Securiti.ai", "Software & IT services", "Karachi", "securiti.ai"),
    ("Motive", "Software & IT services", "Islamabad", "gomotive.com"),
    ("Afiniti", "Software & IT services", "Karachi", "afiniti.com"),
    ("Educative", "Software & IT services", "Lahore", "educative.io"),
    ("Dubizzle Labs (EMPG)", "Software & IT services", "Lahore", "dubizzlelabs.com"),
    ("Turing (remote)", "Software & IT services", "Remote", "turing.com"),
    ("Toptal (remote)", "Software & IT services", "Remote", "toptal.com"),
    ("Crossover (remote)", "Software & IT services", "Remote", "crossover.com"),
    ("Ciklum Pakistan", "Software & IT services", "Islamabad", "ciklum.com"),
    ("Teradata Pakistan", "Software & IT services", "Islamabad", "teradata.com"),
    ("S&P Global Pakistan", "Software & IT services", "Islamabad", "spglobal.com"),
    ("Siemens EDA (Mentor) Lahore", "Software & IT services", "Lahore", "eda.sw.siemens.com"),
    ("VisionX", "Software & IT services", "Islamabad", "visionx.io"),
    ("Programmers Force", "Software & IT services", "Lahore", "pf.com.pk"),
    ("Shufti Pro", "Software & IT services", "Lahore", "shuftipro.com"),
    ("Ephlux", "Software & IT services", "Karachi", "ephlux.com"),
    ("Rockville Technologies", "Software & IT services", "Islamabad", ""),
    ("Royal Cyber", "Software & IT services", "Karachi", "royalcyber.com"),
    ("Visionet Pakistan", "Software & IT services", "Lahore", "visionet.com"),
    ("Kualitatem", "Software & IT services", "Lahore", "kualitatem.com"),
    ("Trillium Information Security Systems", "Software & IT services", "Rawalpindi", "trillium.com.pk"),
    ("Ebryx", "Software & IT services", "Lahore", "ebryx.com"),
    ("Rewterz", "Software & IT services", "Karachi", "rewterz.com"),
    ("Sapphire Consulting Services", "Software & IT services", "Karachi", ""),
    ("CodeNinja", "Software & IT services", "Lahore", "codeninjaconsulting.com"),
    ("Cogilent Solutions", "Software & IT services", "Islamabad", "cogilent.com"),
    ("Cowlar Design Studio", "Software & IT services", "Islamabad", "cowlar.com"),
    ("Remotebase", "Software & IT services", "Lahore", "remotebase.com"),
    ("GigaLabs", "Software & IT services", "Lahore", "gigalabs.co"),
    ("Carbonteq", "Software & IT services", "Lahore", "carbonteq.com"),
    ("Softech Systems", "Software & IT services", "Lahore", "softech.com.pk"),
    ("2B Technologies", "Software & IT services", "Islamabad", ""),
    ("Techverx", "Software & IT services", "Lahore", "techverx.com"),
    ("Nisum Pakistan", "Software & IT services", "Karachi", "nisum.com"),
    ("Tenpearls?dup", "REMOVE", "", ""),

    # ---- AI & data ----
    ("Addo AI", "AI & data", "Lahore", "addo.ai"),
    ("Love For Data", "AI & data", "Karachi", "lovefordata.com"),
    ("Xeven Solutions", "AI & data", "Lahore", "xevensolutions.com"),
    ("Vyro AI", "AI & data", "Islamabad", "vyro.ai"),
    ("Wonder Tree", "AI & data", "Karachi", "wondertree.co"),
    ("Datics AI", "AI & data", "Lahore", "datics.ai"),

    # ---- Gaming & creative tech ----
    ("Mindstorm Studios", "Gaming & creative tech", "Lahore", "mindstormstudios.com"),
    ("Caramel Tech Studios", "Gaming & creative tech", "Lahore", "carameltech.com"),
    ("Frag Games", "Gaming & creative tech", "Lahore", "fraggames.com"),
    ("Game District", "Gaming & creative tech", "Lahore", "gamedistrict.co"),
    ("GenITeam Solutions", "Gaming & creative tech", "Lahore", "geniteam.com"),
    ("Tintash", "Gaming & creative tech", "Lahore", "tintash.com"),

    # ---- Telecom & ISP ----
    ("Jazz", "Telecom & ISP", "Islamabad", "jazz.com.pk"),
    ("Telenor Pakistan", "Telecom & ISP", "Islamabad", "telenor.com.pk"),
    ("Zong (CMPak)", "Telecom & ISP", "Islamabad", "zong.com.pk"),
    ("Ufone", "Telecom & ISP", "Islamabad", "ufone.com"),
    ("PTCL", "Telecom & ISP", "Islamabad", "ptcl.com.pk"),
    ("Nayatel", "Telecom & ISP", "Islamabad", "nayatel.com"),
    ("Cybernet / StormFiber", "Telecom & ISP", "Karachi", "cyber.net.pk"),
    ("Transworld Associates", "Telecom & ISP", "Karachi", "tw1.com"),
    ("Wateen Telecom", "Telecom & ISP", "Lahore", "wateen.com"),
    ("Multinet Pakistan", "Telecom & ISP", "Karachi", "multinet.com.pk"),
    ("Fiberlink", "Telecom & ISP", "Karachi", "fiberlink.net.pk"),
    ("Connect Communications", "Telecom & ISP", "Karachi", ""),
    ("Supernet", "Telecom & ISP", "Karachi", "supernet.com.pk"),
    ("Huawei Pakistan", "Telecom & ISP", "Islamabad", "huawei.com"),
    ("ZTE Pakistan", "Telecom & ISP", "Islamabad", ""),
    ("Ericsson Pakistan", "Telecom & ISP", "Islamabad", "ericsson.com"),
    ("Nokia Pakistan", "Telecom & ISP", "Islamabad", "nokia.com"),
    ("NRTC", "Telecom & ISP", "Haripur", "nrtc.com.pk"),

    # ---- Fintech & payments ----
    ("Easypaisa (Telenor Microfinance Bank)", "Fintech & payments", "Karachi", "easypaisa.com.pk"),
    ("JazzCash (Mobilink Microfinance Bank)", "Fintech & payments", "Islamabad", "jazzcash.com.pk"),
    ("SadaPay", "Fintech & payments", "Islamabad", "sadapay.pk"),
    ("NayaPay", "Fintech & payments", "Karachi", "nayapay.com"),
    ("Abhi", "Fintech & payments", "Karachi", "abhi.com.pk"),
    ("CreditBook", "Fintech & payments", "Karachi", "creditbook.pk"),
    ("Finja", "Fintech & payments", "Lahore", "finja.pk"),
    ("Oraan", "Fintech & payments", "Karachi", "oraan.com"),
    ("PayFast (Avanza)", "Fintech & payments", "Karachi", "gopayfast.com"),
    ("1LINK", "Fintech & payments", "Karachi", "1link.net.pk"),
    ("NIFT", "Fintech & payments", "Karachi", "nift.pk"),
    ("Haball", "Fintech & payments", "Karachi", "haball.pk"),
    ("Neem", "Fintech & payments", "Karachi", "neem.io"),
    ("Keenu (Wemsol)", "Fintech & payments", "Karachi", "keenu.pk"),
    ("Foree", "Fintech & payments", "Karachi", ""),
    ("Zindigi (JS Bank)", "Fintech & payments", "Karachi", "zindigi.com"),
    ("KTrade Securities", "Fintech & payments", "Karachi", "ktrade.pk"),
    ("Safepay", "Fintech & payments", "Karachi", "getsafepay.com"),
    ("Paymob Pakistan", "Fintech & payments", "Karachi", "paymob.com"),
    ("PayPro", "Fintech & payments", "Karachi", "paypro.com.pk"),

    # ---- Banking ----
    ("Habib Bank Limited (HBL)", "Banking", "Karachi", "hbl.com"),
    ("United Bank Limited (UBL)", "Banking", "Karachi", "ubldigital.com"),
    ("MCB Bank", "Banking", "Lahore", "mcb.com.pk"),
    ("Allied Bank (ABL)", "Banking", "Lahore", "abl.com"),
    ("National Bank of Pakistan", "Banking", "Karachi", "nbp.com.pk"),
    ("Bank Alfalah", "Banking", "Karachi", "bankalfalah.com"),
    ("Meezan Bank", "Banking", "Karachi", "meezanbank.com"),
    ("Faysal Bank", "Banking", "Karachi", "faysalbank.com"),
    ("Askari Bank", "Banking", "Rawalpindi", "askaribank.com"),
    ("Bank of Punjab", "Banking", "Lahore", "bop.com.pk"),
    ("JS Bank", "Banking", "Karachi", "jsbl.com"),
    ("Soneri Bank", "Banking", "Karachi", "soneribank.com"),
    ("Standard Chartered Pakistan", "Banking", "Karachi", "sc.com"),
    ("Habib Metropolitan Bank", "Banking", "Karachi", "habibmetro.com"),
    ("BankIslami", "Banking", "Karachi", "bankislami.com.pk"),
    ("Dubai Islamic Bank Pakistan", "Banking", "Karachi", "dibpak.com"),
    ("Al Baraka Bank Pakistan", "Banking", "Karachi", "albaraka.com.pk"),
    ("Sindh Bank", "Banking", "Karachi", "sindhbank.com.pk"),
    ("Bank of Khyber", "Banking", "Peshawar", "bok.com.pk"),
    ("Zarai Taraqiati Bank (ZTBL)", "Banking", "Islamabad", "ztbl.com.pk"),
    ("U Microfinance Bank", "Banking", "Islamabad", "ubank.com.pk"),
    ("Khushhali Microfinance Bank", "Banking", "Islamabad", ""),
    ("HBL Microfinance Bank", "Banking", "Islamabad", "hblmfb.com"),
    ("FINCA Microfinance Bank", "Banking", "Lahore", "finca.pk"),
    ("NRSP Microfinance Bank", "Banking", "Bahawalpur", "nrspbank.com"),
    ("State Bank of Pakistan", "Banking", "Karachi", "sbp.org.pk"),

    # ---- Insurance & finance ----
    ("Pakistan Stock Exchange", "Insurance & finance", "Karachi", "psx.com.pk"),
    ("Central Depository Company (CDC)", "Insurance & finance", "Karachi", "cdcpakistan.com"),
    ("NCCPL", "Insurance & finance", "Karachi", "nccpl.com.pk"),
    ("Arif Habib Limited", "Insurance & finance", "Karachi", "arifhabibltd.com"),
    ("JS Global Capital", "Insurance & finance", "Karachi", "jsgcl.com"),
    ("AKD Securities", "Insurance & finance", "Karachi", "akdsecurities.net"),
    ("Topline Securities", "Insurance & finance", "Karachi", "topline.com.pk"),
    ("Intermarket Securities", "Insurance & finance", "Karachi", ""),
    ("BMA Capital", "Insurance & finance", "Karachi", "bmacapital.com"),
    ("Al Meezan Investments", "Insurance & finance", "Karachi", "almeezangroup.com"),
    ("NBP Funds", "Insurance & finance", "Karachi", "nbpfunds.com"),
    ("UBL Funds", "Insurance & finance", "Karachi", "ublfunds.com.pk"),
    ("HBL Asset Management", "Insurance & finance", "Karachi", ""),
    ("Lucky Investments", "Insurance & finance", "Karachi", ""),
    ("PACRA", "Insurance & finance", "Lahore", "pacra.com"),
    ("VIS Credit Rating", "Insurance & finance", "Karachi", "vis.com.pk"),
    ("Jubilee Life Insurance", "Insurance & finance", "Karachi", "jubileelife.com"),
    ("Jubilee General Insurance", "Insurance & finance", "Karachi", "jubileegeneral.com.pk"),
    ("EFU Life", "Insurance & finance", "Karachi", "efulife.com"),
    ("EFU General", "Insurance & finance", "Karachi", "efuinsurance.com"),
    ("Adamjee Insurance", "Insurance & finance", "Karachi", "adamjeeinsurance.com"),
    ("State Life Insurance", "Insurance & finance", "Karachi", "statelife.com.pk"),
    ("IGI Insurance", "Insurance & finance", "Karachi", "igiinsurance.com.pk"),
    ("TPL Insurance", "Insurance & finance", "Karachi", "tplinsurance.com"),
    ("Salaam Takaful", "Insurance & finance", "Karachi", "salaamtakaful.com"),
    ("Pak-Qatar Takaful", "Insurance & finance", "Karachi", "pakqatar.com.pk"),

    # ---- E-commerce & marketplaces ----
    ("Daraz", "E-commerce & marketplaces", "Karachi", "daraz.pk"),
    ("PakWheels", "E-commerce & marketplaces", "Lahore", "pakwheels.com"),
    ("Zameen.com", "E-commerce & marketplaces", "Lahore", "zameen.com"),
    ("Graana", "E-commerce & marketplaces", "Islamabad", "graana.com"),
    ("OLX Pakistan", "E-commerce & marketplaces", "Karachi", "olx.com.pk"),
    ("PriceOye", "E-commerce & marketplaces", "Islamabad", "priceoye.pk"),
    ("Telemart", "E-commerce & marketplaces", "Karachi", "telemart.pk"),
    ("iShopping", "E-commerce & marketplaces", "Karachi", "ishopping.pk"),
    ("Shophive", "E-commerce & marketplaces", "Lahore", "shophive.com"),
    ("Laam", "E-commerce & marketplaces", "Lahore", "laam.pk"),
    ("Bagallery", "E-commerce & marketplaces", "Lahore", "bagallery.com"),
    ("Foodpanda Pakistan", "E-commerce & marketplaces", "Karachi", "foodpanda.pk"),
    ("Krave Mart", "E-commerce & marketplaces", "Karachi", "kravemart.com"),
    ("GrocerApp", "E-commerce & marketplaces", "Lahore", "grocerapp.pk"),
    ("Dastgyr", "E-commerce & marketplaces", "Karachi", "dastgyr.com"),
    ("Bazaar Technologies", "E-commerce & marketplaces", "Karachi", "bazaartech.com"),
    ("Retailo", "E-commerce & marketplaces", "Karachi", "retailo.co"),
    ("Jugnu", "E-commerce & marketplaces", "Lahore", "jugnu.pk"),
    ("Tajir", "E-commerce & marketplaces", "Lahore", "tajir.app"),
    ("Markaz", "E-commerce & marketplaces", "Karachi", "markaz.app"),
    ("DealCart", "E-commerce & marketplaces", "Karachi", "dealcart.io"),
    ("Zaraye", "E-commerce & marketplaces", "Karachi", "zaraye.co"),
    ("XStak", "E-commerce & marketplaces", "Lahore", "xstak.com"),
    ("Salesflo", "E-commerce & marketplaces", "Karachi", "salesflo.com"),
    ("ConsoliAds", "E-commerce & marketplaces", "Islamabad", "consoliads.com"),
    ("Dukan", "E-commerce & marketplaces", "Karachi", "dukan.pk"),
    ("Bookme", "E-commerce & marketplaces", "Lahore", "bookme.pk"),
    ("Sastaticket", "E-commerce & marketplaces", "Karachi", "sastaticket.pk"),
    ("FindMyAdventure", "E-commerce & marketplaces", "Karachi", "findmyadventure.pk"),

    # ---- Mobility ----
    ("Careem", "Mobility", "Karachi", "careem.com"),
    ("Bykea", "Mobility", "Karachi", "bykea.com"),
    ("inDrive Pakistan", "Mobility", "Karachi", "indrive.com"),
    ("Yango Pakistan", "Mobility", "Karachi", "yango.com"),
    ("ezBike", "Mobility", "Islamabad", "ezbike.pk"),

    # ---- Logistics & delivery ----
    ("TCS", "Logistics & delivery", "Karachi", "tcsexpress.com"),
    ("Leopards Courier", "Logistics & delivery", "Karachi", "leopardscourier.com"),
    ("M&P Express Logistics", "Logistics & delivery", "Karachi", "mulphilog.com"),
    ("DHL Pakistan", "Logistics & delivery", "Karachi", "dhl.com"),
    ("Gerry's (FedEx Pakistan)", "Logistics & delivery", "Karachi", "gerrys.com"),
    ("BlueEx", "Logistics & delivery", "Karachi", "blue-ex.com"),
    ("Trax", "Logistics & delivery", "Karachi", "trax.pk"),
    ("PostEx", "Logistics & delivery", "Lahore", "postex.pk"),
    ("Rider", "Logistics & delivery", "Karachi", "withrider.com"),
    ("Swyft Logistics", "Logistics & delivery", "Lahore", "swyftlogistics.com"),
    ("Truck It In", "Logistics & delivery", "Karachi", "truckitin.com"),
    ("Bridgelinx", "Logistics & delivery", "Lahore", "bridgelinxpk.com"),
    ("CallCourier", "Logistics & delivery", "Lahore", "callcourier.com.pk"),
    ("Pakistan Post", "Logistics & delivery", "Islamabad", "pakpost.gov.pk"),
    ("Daewoo FastEx", "Logistics & delivery", "Lahore", "daewoo.com.pk"),

    # ---- Health tech ----
    ("Sehat Kahani", "Health tech", "Karachi", "sehatkahani.com"),
    ("Marham", "Health tech", "Lahore", "marham.pk"),
    ("oladoc", "Health tech", "Lahore", "oladoc.com"),
    ("Dawaai", "Health tech", "Karachi", "dawaai.pk"),
    ("Healthwire", "Health tech", "Lahore", "healthwire.pk"),
    ("MedIQ", "Health tech", "Islamabad", "mediq.com.pk"),

    # ---- Hospitals & labs ----
    ("Aga Khan University Hospital", "Hospitals & labs", "Karachi", "aku.edu"),
    ("Shaukat Khanum Memorial Cancer Hospital", "Hospitals & labs", "Lahore", "shaukatkhanum.org.pk"),
    ("Indus Hospital & Health Network", "Hospitals & labs", "Karachi", "indushospital.org.pk"),
    ("Shifa International Hospital", "Hospitals & labs", "Islamabad", "shifa.com.pk"),
    ("Evercare Hospital", "Hospitals & labs", "Lahore", "evercare.pk"),
    ("Doctors Hospital", "Hospitals & labs", "Lahore", "doctorshospital.com.pk"),
    ("Liaquat National Hospital", "Hospitals & labs", "Karachi", "lnh.edu.pk"),
    ("South City Hospital", "Hospitals & labs", "Karachi", "southcityhospital.org"),
    ("Hameed Latif Hospital", "Hospitals & labs", "Lahore", "hameedlatifhospital.com"),
    ("Chughtai Lab", "Hospitals & labs", "Lahore", "chughtailab.com"),
    ("Islamabad Diagnostic Centre (IDC)", "Hospitals & labs", "Islamabad", "idc.net.pk"),
    ("Excel Labs", "Hospitals & labs", "Islamabad", "excel-labs.com"),
    ("Shalamar Hospital", "Hospitals & labs", "Lahore", "shalamarhospital.org.pk"),
    ("Fatima Memorial Hospital", "Hospitals & labs", "Lahore", "fmhcmd.edu.pk"),
    ("Ziauddin Hospital", "Hospitals & labs", "Karachi", "ziauddinhospital.com"),
    ("Pakistan Kidney & Liver Institute (PKLI)", "Hospitals & labs", "Lahore", "pkli.org.pk"),
    ("NICVD", "Hospitals & labs", "Karachi", "nicvd.org"),
    ("Rehman Medical Institute", "Hospitals & labs", "Peshawar", "rmi.edu.pk"),

    # ---- Pharma ----
    ("Getz Pharma", "Pharma", "Karachi", "getzpharma.com"),
    ("The Searle Company", "Pharma", "Karachi", "searlecompany.com"),
    ("Sami Pharmaceuticals", "Pharma", "Karachi", "samipharmapk.com"),
    ("Martin Dow", "Pharma", "Karachi", "martindow.com"),
    ("Hilton Pharma", "Pharma", "Karachi", "hiltonpharma.com"),
    ("PharmEvo", "Pharma", "Karachi", "pharmevo.biz"),
    ("Highnoon Laboratories", "Pharma", "Lahore", "highnoon.com.pk"),
    ("Ferozsons Laboratories", "Pharma", "Rawalpindi", "ferozsons-labs.com"),
    ("AGP Limited", "Pharma", "Karachi", "agp.com.pk"),
    ("GSK Pakistan", "Pharma", "Karachi", "pk.gsk.com"),
    ("Abbott Pakistan", "Pharma", "Karachi", "abbott.com.pk"),
    ("Pfizer Pakistan", "Pharma", "Karachi", "pfizer.com.pk"),
    ("Novartis Pakistan", "Pharma", "Karachi", "novartis.com"),
    ("Bayer Pakistan", "Pharma", "Karachi", "bayer.com.pk"),
    ("Sanofi Pakistan", "Pharma", "Karachi", "sanofi.pk"),
    ("Haleon Pakistan", "Pharma", "Karachi", "haleon.com"),
    ("OBS Pakistan", "Pharma", "Karachi", "obs-group.com"),
    ("Macter International", "Pharma", "Karachi", "macter.com"),
    ("Indus Pharma", "Pharma", "Karachi", "induspharma.com"),
    ("Bosch Pharmaceuticals", "Pharma", "Karachi", "boschpharma.com"),
    ("CCL Pharmaceuticals", "Pharma", "Lahore", "cclpharma.com"),
    ("Genix Pharma", "Pharma", "Karachi", "genixpharma.com"),
    ("Herbion", "Pharma", "Karachi", "herbion.com"),
    ("Nabiqasim", "Pharma", "Karachi", "nabiqasim.com"),
    ("Atco Laboratories", "Pharma", "Karachi", "atcolab.com"),
    ("Barrett Hodgson", "Pharma", "Karachi", "barretthodgson.com"),

    # ---- FMCG & food ----
    ("Nestlé Pakistan", "FMCG & food", "Lahore", "nestle.pk"),
    ("Unilever Pakistan", "FMCG & food", "Karachi", "unilever.pk"),
    ("Procter & Gamble Pakistan", "FMCG & food", "Karachi", "pg.com"),
    ("Reckitt Pakistan", "FMCG & food", "Karachi", "reckitt.com"),
    ("Colgate-Palmolive Pakistan", "FMCG & food", "Karachi", "colgate.com.pk"),
    ("L'Oréal Pakistan", "FMCG & food", "Karachi", "loreal.com"),
    ("PepsiCo Pakistan", "FMCG & food", "Lahore", "pepsico.com"),
    ("Coca-Cola Beverages Pakistan (CCI)", "FMCG & food", "Lahore", "cci.com.tr"),
    ("National Foods", "FMCG & food", "Karachi", "nfoods.com"),
    ("Shan Foods", "FMCG & food", "Karachi", "shanfoods.com"),
    ("FrieslandCampina Engro", "FMCG & food", "Karachi", "frieslandcampina.com.pk"),
    ("Fauji Foods", "FMCG & food", "Lahore", "faujifoods.com"),
    ("Dalda Foods", "FMCG & food", "Karachi", "dalda.com.pk"),
    ("Ismail Industries (CandyLand/Bisconni)", "FMCG & food", "Karachi", "ismailindustries.com.pk"),
    ("English Biscuit Manufacturers (Peek Freans)", "FMCG & food", "Karachi", "ebm.com.pk"),
    ("Continental Biscuits (LU)", "FMCG & food", "Karachi", "cbl.com.pk"),
    ("Hilal Foods", "FMCG & food", "Karachi", "hilalfoods.com.pk"),
    ("Shezan International", "FMCG & food", "Lahore", "shezan.com"),
    ("Mitchell's Fruit Farms", "FMCG & food", "Lahore", "mitchells.com.pk"),
    ("Murree Brewery", "FMCG & food", "Rawalpindi", "murreebrewery.com"),
    ("Tapal Tea", "FMCG & food", "Karachi", "tapaltea.com"),
    ("Habib Oil Mills", "FMCG & food", "Karachi", "hom.com.pk"),
    ("Matco Foods", "FMCG & food", "Karachi", "matcofoods.com"),
    ("Al Shaheer Corporation (Meat One)", "FMCG & food", "Karachi", "alshaheer.com.pk"),
    ("K&N's", "FMCG & food", "Karachi", "kandns.com"),
    ("Simply Sufi", "FMCG & food", "Lahore", "simplysufi.com"),
    ("Mondelez Pakistan", "FMCG & food", "Karachi", "mondelezinternational.com"),
    ("Haleeb Foods", "FMCG & food", "Lahore", "haleebfoods.com"),

    # ---- Food chains & QSR ----
    ("McDonald's Pakistan (Siza Foods)", "Food chains & QSR", "Lahore", "mcdonalds.com.pk"),
    ("KFC Pakistan (Cupola)", "Food chains & QSR", "Karachi", "kfcpakistan.com"),
    ("Pizza Hut Pakistan", "Food chains & QSR", "Karachi", "pizzahut.com.pk"),
    ("Domino's Pakistan", "Food chains & QSR", "Karachi", "dominos.com.pk"),
    ("Hardee's Pakistan", "Food chains & QSR", "Lahore", "hardees.com.pk"),
    ("Burger King Pakistan", "Food chains & QSR", "Karachi", ""),
    ("Subway Pakistan", "Food chains & QSR", "Lahore", ""),
    ("OPTP", "Food chains & QSR", "Karachi", "optp.biz"),
    ("Broadway Pizza", "Food chains & QSR", "Karachi", "broadwaypizza.com.pk"),
    ("14th Street Pizza", "Food chains & QSR", "Karachi", "14thstreetpizza.com"),
    ("Kababjees", "Food chains & QSR", "Karachi", "kababjees.com"),
    ("BarBQ Tonight", "Food chains & QSR", "Karachi", "bbqtonight.com.pk"),
    ("Savour Foods", "Food chains & QSR", "Rawalpindi", "savourfoods.com.pk"),
    ("Student Biryani", "Food chains & QSR", "Karachi", "studentbiryani.com"),
    ("Cheezious", "Food chains & QSR", "Islamabad", "cheezious.com"),
    ("Howdy", "Food chains & QSR", "Lahore", "howdy.pk"),
    ("Gloria Jean's Coffees Pakistan", "Food chains & QSR", "Lahore", ""),
    ("Chaaye Khana", "Food chains & QSR", "Islamabad", ""),
    ("Dunkin' Pakistan", "Food chains & QSR", "Lahore", ""),
    ("Tim Hortons Pakistan", "Food chains & QSR", "Lahore", ""),

    # ---- Retail & fashion ----
    ("Khaadi", "Retail & fashion", "Karachi", "khaadi.com"),
    ("Gul Ahmed (Ideas)", "Retail & fashion", "Karachi", "gulahmedshop.com"),
    ("Sapphire Retail", "Retail & fashion", "Lahore", "pk.sapphireonline.pk"),
    ("Alkaram Studio", "Retail & fashion", "Karachi", "alkaramstudio.com"),
    ("Nishat Linen", "Retail & fashion", "Lahore", "nishatlinen.com"),
    ("Sana Safinaz", "Retail & fashion", "Karachi", "sanasafinaz.com"),
    ("Outfitters", "Retail & fashion", "Lahore", "outfitters.com.pk"),
    ("Breakout", "Retail & fashion", "Lahore", "breakout.com.pk"),
    ("Bonanza Satrangi", "Retail & fashion", "Karachi", "bonanzasatrangi.com"),
    ("J. (Junaid Jamshed)", "Retail & fashion", "Karachi", "junaidjamshed.com"),
    ("Limelight", "Retail & fashion", "Lahore", "limelight.pk"),
    ("Beechtree", "Retail & fashion", "Lahore", "beechtree.pk"),
    ("Generation", "Retail & fashion", "Lahore", "generation.com.pk"),
    ("Ego", "Retail & fashion", "Lahore", "wearego.com"),
    ("Zellbury", "Retail & fashion", "Lahore", "zellbury.com"),
    ("Chinyere", "Retail & fashion", "Karachi", ""),
    ("Cross Stitch", "Retail & fashion", "Lahore", "crossstitch.pk"),
    ("Stylo Shoes", "Retail & fashion", "Lahore", "stylo.pk"),
    ("Borjan", "Retail & fashion", "Lahore", "borjan.com.pk"),
    ("Ndure (Servis)", "Retail & fashion", "Lahore", "ndure.com"),
    ("ECS", "Retail & fashion", "Lahore", "ecs.com.pk"),
    ("Insignia", "Retail & fashion", "Lahore", "insignia.com.pk"),
    ("Hush Puppies Pakistan", "Retail & fashion", "Lahore", "hushpuppies.com.pk"),
    ("Interwood", "Retail & fashion", "Lahore", "interwood.pk"),
    ("Habitt", "Retail & fashion", "Karachi", "habitt.com"),
    ("ChenOne", "Retail & fashion", "Multan", "chenone.com"),
    ("Metro Pakistan", "Retail & fashion", "Lahore", "metro-online.pk"),
    ("Carrefour Pakistan (MAF)", "Retail & fashion", "Karachi", "carrefour.pk"),
    ("Imtiaz Super Market", "Retail & fashion", "Karachi", "imtiaz.com.pk"),
    ("Chase Up", "Retail & fashion", "Karachi", "chaseup.com.pk"),
    ("Al-Fatah", "Retail & fashion", "Lahore", "alfatah.pk"),
    ("Naheed Super Market", "Retail & fashion", "Karachi", "naheed.pk"),
    ("Springs Stores", "Retail & fashion", "Karachi", "springs.com.pk"),
    ("Save Mart", "Retail & fashion", "Islamabad", "savemart.pk"),
    ("CSD (Canteen Stores Department)", "Retail & fashion", "Rawalpindi", "csd.gov.pk"),
    ("Utility Stores Corporation", "Retail & fashion", "Islamabad", "usc.org.pk"),

    # ---- Textiles & apparel ----
    ("Interloop", "Textiles & apparel", "Faisalabad", "interloop-pk.com"),
    ("Nishat Mills", "Textiles & apparel", "Lahore", "nishatmillsltd.com"),
    ("Nishat Chunian", "Textiles & apparel", "Lahore", "nishat.net"),
    ("Gul Ahmed Textile Mills", "Textiles & apparel", "Karachi", "gulahmed.com"),
    ("Sapphire Textile Mills", "Textiles & apparel", "Lahore", "sapphire.com.pk"),
    ("Sadaqat Limited", "Textiles & apparel", "Faisalabad", "sadaqatlimited.com"),
    ("Crescent Textile Mills", "Textiles & apparel", "Faisalabad", "crescenttextile.com"),
    ("Kohinoor Textile Mills", "Textiles & apparel", "Rawalpindi", ""),
    ("Masood Textile Mills", "Textiles & apparel", "Faisalabad", "masoodtextile.com"),
    ("US Apparel & Textiles", "Textiles & apparel", "Lahore", "usapparel.com.pk"),
    ("Style Textile", "Textiles & apparel", "Lahore", "styletextile.com"),
    ("Artistic Milliners", "Textiles & apparel", "Karachi", "artisticmilliners.com"),
    ("Soorty Enterprises", "Textiles & apparel", "Karachi", "soorty.com"),
    ("Siddiqsons", "Textiles & apparel", "Karachi", "siddiqsons.com"),
    ("Feroze1888 Mills", "Textiles & apparel", "Karachi", "feroze1888.com"),
    ("Ibrahim Fibres", "Textiles & apparel", "Faisalabad", "ibrahimfibres.com"),

    # ---- Manufacturing & industrial ----
    ("Engro Corporation", "Manufacturing & industrial", "Karachi", "engro.com"),
    ("Engro Fertilizers", "Manufacturing & industrial", "Karachi", "engrofertilizers.com"),
    ("Engro Polymer & Chemicals", "Manufacturing & industrial", "Karachi", "engropolymer.com"),
    ("Fatima Group", "Manufacturing & industrial", "Lahore", "fatima-group.com"),
    ("Fauji Fertilizer Company (FFC)", "Manufacturing & industrial", "Rawalpindi", "ffc.com.pk"),
    ("Fauji Foundation", "Manufacturing & industrial", "Rawalpindi", "fauji.org.pk"),
    ("Lucky Cement", "Manufacturing & industrial", "Karachi", "lucky-cement.com"),
    ("Lucky Core Industries", "Manufacturing & industrial", "Karachi", "luckycore.com"),
    ("DG Khan Cement", "Manufacturing & industrial", "Lahore", "dgcement.com"),
    ("Maple Leaf Cement", "Manufacturing & industrial", "Lahore", "kmlg.com"),
    ("Bestway Cement", "Manufacturing & industrial", "Islamabad", "bestway.com.pk"),
    ("Cherat Cement", "Manufacturing & industrial", "Nowshera", "gfg.com.pk"),
    ("Kohat Cement", "Manufacturing & industrial", "Kohat", "kohatcement.com"),
    ("Attock Cement", "Manufacturing & industrial", "Karachi", "attockcement.com"),
    ("Pioneer Cement", "Manufacturing & industrial", "Lahore", ""),
    ("Packages Limited", "Manufacturing & industrial", "Lahore", "packages.com.pk"),
    ("Century Paper & Board", "Manufacturing & industrial", "Karachi", "centurypaper.com.pk"),
    ("Ghani Glass", "Manufacturing & industrial", "Lahore", "ghaniglass.com"),
    ("Tariq Glass", "Manufacturing & industrial", "Lahore", "tariqglass.com"),
    ("International Industries (IIL)", "Manufacturing & industrial", "Karachi", "iil.com.pk"),
    ("International Steels (ISL)", "Manufacturing & industrial", "Karachi", "isl.com.pk"),
    ("Amreli Steels", "Manufacturing & industrial", "Karachi", "amrelisteels.com"),
    ("Mughal Steel", "Manufacturing & industrial", "Lahore", "mughalsteel.com"),
    ("Agha Steel Industries", "Manufacturing & industrial", "Karachi", "aghasteel.com"),
    ("Aisha Steel Mills", "Manufacturing & industrial", "Karachi", ""),
    ("Pakistan Cables", "Manufacturing & industrial", "Karachi", "pakistancables.com"),
    ("Fast Cables", "Manufacturing & industrial", "Lahore", "fastcables.com"),
    ("Thermosole Industries", "Manufacturing & industrial", "Karachi", ""),
    ("Descon", "Manufacturing & industrial", "Lahore", "descon.com"),
    ("NESPAK", "Manufacturing & industrial", "Lahore", "nespak.com.pk"),

    # ---- Auto & engineering ----
    ("Indus Motor Company (Toyota)", "Auto & engineering", "Karachi", "toyota-indus.com"),
    ("Pak Suzuki Motor", "Auto & engineering", "Karachi", "paksuzuki.com.pk"),
    ("Honda Atlas Cars", "Auto & engineering", "Lahore", "honda.com.pk"),
    ("Atlas Honda (motorcycles)", "Auto & engineering", "Karachi", "atlashonda.com.pk"),
    ("Millat Tractors", "Auto & engineering", "Lahore", "millat.com.pk"),
    ("Al-Ghazi Tractors", "Auto & engineering", "Karachi", "alghazitractors.com"),
    ("Master Motors", "Auto & engineering", "Karachi", "mastermotor.com.pk"),
    ("Hyundai Nishat Motor", "Auto & engineering", "Lahore", "hyundai-nishat.com"),
    ("Lucky Motor Corporation (Kia)", "Auto & engineering", "Karachi", "kia.com.pk"),
    ("Sazgar Engineering", "Auto & engineering", "Lahore", "sazgarautos.com"),
    ("Yamaha Motor Pakistan", "Auto & engineering", "Karachi", "yamaha-motor.com.pk"),
    ("Ghandhara Industries (Isuzu)", "Auto & engineering", "Karachi", "ghandhara.com.pk"),
    ("Millat Equipment", "Auto & engineering", "Lahore", ""),
    ("Panther Tyres", "Auto & engineering", "Lahore", "panthertyres.com"),
    ("General Tyre", "Auto & engineering", "Karachi", "generaltyre.com.pk"),
    ("Service Industries (Servis)", "Auto & engineering", "Lahore", "servisgroup.com"),
    ("Bata Pakistan", "Auto & engineering", "Lahore", "bata.com.pk"),

    # ---- Electronics & appliances ----
    ("Dawlance", "Electronics & appliances", "Karachi", "dawlance.com.pk"),
    ("Haier Pakistan", "Electronics & appliances", "Lahore", "haier.com.pk"),
    ("Orient Electronics", "Electronics & appliances", "Lahore", "orient.com.pk"),
    ("PEL (Pak Elektron)", "Electronics & appliances", "Lahore", "pel.com.pk"),
    ("Waves", "Electronics & appliances", "Lahore", "waves.net.pk"),
    ("Super Asia", "Electronics & appliances", "Gujranwala", "superasia.com.pk"),
    ("Homage", "Electronics & appliances", "Lahore", "homage.pk"),
    ("EcoStar (DWP Group)", "Electronics & appliances", "Lahore", "ecostar.com.pk"),
    ("DWP Group", "Electronics & appliances", "Lahore", "dwp.com.pk"),
    ("TCL Pakistan", "Electronics & appliances", "Lahore", "tcl.com.pk"),
    ("Samsung Pakistan", "Electronics & appliances", "Karachi", "samsung.com/pk"),
    ("Air Link Communication", "Electronics & appliances", "Lahore", "airlinkcommunication.net"),
    ("Transsion Pakistan (Infinix/Tecno)", "Electronics & appliances", "Karachi", ""),
    ("vivo Pakistan", "Electronics & appliances", "Lahore", "vivo.com/pk"),
    ("OPPO Pakistan", "Electronics & appliances", "Lahore", "oppo.com/pk"),
    ("realme Pakistan", "Electronics & appliances", "Lahore", "realme.com/pk"),
    ("GFC Fans", "Electronics & appliances", "Gujrat", "gfcfans.com"),
    ("Pak Fan", "Electronics & appliances", "Gujrat", "pakfan.com"),

    # ---- Energy & utilities ----
    ("Pakistan State Oil (PSO)", "Energy & utilities", "Karachi", "psopk.com"),
    ("Wafi Energy (Shell Pakistan)", "Energy & utilities", "Karachi", "shell.com.pk"),
    ("Total PARCO", "Energy & utilities", "Karachi", "totalparco.com.pk"),
    ("Attock Petroleum", "Energy & utilities", "Rawalpindi", "apl.com.pk"),
    ("GO (Gas & Oil Pakistan)", "Energy & utilities", "Lahore", "gopetroleum.com.pk"),
    ("Cnergyico", "Energy & utilities", "Karachi", "cnergyico.pk"),
    ("PARCO", "Energy & utilities", "Karachi", "parco.com.pk"),
    ("Attock Refinery (ARL)", "Energy & utilities", "Rawalpindi", "arl.com.pk"),
    ("National Refinery (NRL)", "Energy & utilities", "Karachi", "nrlpak.com"),
    ("Pakistan Refinery (PRL)", "Energy & utilities", "Karachi", "prl.com.pk"),
    ("OGDCL", "Energy & utilities", "Islamabad", "ogdcl.com"),
    ("Pakistan Petroleum Limited (PPL)", "Energy & utilities", "Karachi", "ppl.com.pk"),
    ("Mari Energies", "Energy & utilities", "Islamabad", "marienergies.com.pk"),
    ("MOL Pakistan", "Energy & utilities", "Islamabad", "molgroup.info"),
    ("United Energy Pakistan (UEP)", "Energy & utilities", "Karachi", "uep.com.pk"),
    ("SNGPL", "Energy & utilities", "Lahore", "sngpl.com.pk"),
    ("SSGC", "Energy & utilities", "Karachi", "ssgc.com.pk"),
    ("K-Electric", "Energy & utilities", "Karachi", "ke.com.pk"),
    ("HUBCO", "Energy & utilities", "Karachi", "hubpower.com"),
    ("KAPCO", "Energy & utilities", "Lahore", "kapco.com.pk"),
    ("Nishat Power", "Energy & utilities", "Lahore", ""),
    ("Engro Energy", "Energy & utilities", "Karachi", "engroenergy.com"),
    ("Sindh Engro Coal Mining (SECMC)", "Energy & utilities", "Karachi", "secmc.com.pk"),
    ("Reon Energy", "Energy & utilities", "Karachi", "reonenergy.com"),
    ("SkyElectric", "Energy & utilities", "Islamabad", "skyelectric.com"),
    ("Premier Energy", "Energy & utilities", "Lahore", "premierenergy.com.pk"),
    ("Nizam Energy", "Energy & utilities", "Karachi", "nizamenergy.com"),
    ("WAPDA", "Energy & utilities", "Lahore", "wapda.gov.pk"),
    ("NTDC", "Energy & utilities", "Lahore", "ntdc.gov.pk"),

    # ---- Media ----
    ("Jang Media Group / Geo", "Media", "Karachi", "jang.com.pk"),
    ("Dawn Media Group", "Media", "Karachi", "dawn.com"),
    ("ARY Digital Network", "Media", "Karachi", "arydigital.tv"),
    ("Hum Network", "Media", "Karachi", "humnetwork.tv"),
    ("Express Media Group", "Media", "Lahore", "express.com.pk"),
    ("Samaa TV", "Media", "Karachi", "samaa.tv"),
    ("Dunya Media Group", "Media", "Lahore", "dunyanews.tv"),
    ("Aaj TV", "Media", "Karachi", "aaj.tv"),
    ("Walee Technologies", "Media", "Lahore", "walee.pk"),
    ("IAL Saatchi & Saatchi", "Media", "Karachi", ""),

    # ---- Edtech ----
    ("Knowledge Platform", "Edtech", "Islamabad", "knowledgeplatform.com"),
    ("Maqsad", "Edtech", "Karachi", "maqsad.io"),
    ("Abwaab", "Edtech", "Lahore", "abwaab.com"),
    ("Taleemabad (Orenda)", "Edtech", "Islamabad", "taleemabad.com"),
    ("Edkasa", "Edtech", "Lahore", "edkasa.com"),
    ("Nearpeer", "Edtech", "Lahore", "nearpeer.org"),
    ("Sabaq", "Edtech", "Karachi", "sabaq.pk"),
    ("Out-Class", "Edtech", "Karachi", "out-class.org"),
    ("PNY Trainings", "Edtech", "Lahore", "pnytrainings.com"),
    ("KIPS Education System", "Edtech", "Lahore", "kips.edu.pk"),

    # ---- Universities & education ----
    ("LUMS", "Universities & education", "Lahore", "lums.edu.pk"),
    ("NUST", "Universities & education", "Islamabad", "nust.edu.pk"),
    ("FAST-NUCES", "Universities & education", "Islamabad", "nu.edu.pk"),
    ("GIKI", "Universities & education", "Topi", "giki.edu.pk"),
    ("IBA Karachi", "Universities & education", "Karachi", "iba.edu.pk"),
    ("Habib University", "Universities & education", "Karachi", "habib.edu.pk"),
    ("UMT", "Universities & education", "Lahore", "umt.edu.pk"),
    ("UCP", "Universities & education", "Lahore", "ucp.edu.pk"),
    ("COMSATS University", "Universities & education", "Islamabad", "comsats.edu.pk"),
    ("Air University", "Universities & education", "Islamabad", "au.edu.pk"),
    ("Bahria University", "Universities & education", "Islamabad", "bahria.edu.pk"),
    ("UET Lahore", "Universities & education", "Lahore", "uet.edu.pk"),
    ("PIEAS", "Universities & education", "Islamabad", "pieas.edu.pk"),
    ("ITU Punjab", "Universities & education", "Lahore", "itu.edu.pk"),
    ("NED University", "Universities & education", "Karachi", "neduet.edu.pk"),
    ("SZABIST", "Universities & education", "Karachi", "szabist.edu.pk"),
    ("Iqra University", "Universities & education", "Karachi", "iqra.edu.pk"),
    ("Riphah International University", "Universities & education", "Islamabad", "riphah.edu.pk"),
    ("Superior University", "Universities & education", "Lahore", "superior.edu.pk"),
    ("University of Lahore", "Universities & education", "Lahore", "uol.edu.pk"),
    ("Institute of Space Technology", "Universities & education", "Islamabad", "ist.edu.pk"),
    ("Beaconhouse School System", "Universities & education", "Lahore", "beaconhouse.net"),
    ("The City School", "Universities & education", "Lahore", "thecityschool.edu.pk"),
    ("Roots International Schools", "Universities & education", "Islamabad", "rootsinternational.edu.pk"),
    ("Punjab Group of Colleges", "Universities & education", "Lahore", "pgc.edu"),

    # ---- Travel & hospitality ----
    ("Pakistan International Airlines (PIA)", "Travel & hospitality", "Karachi", "piac.com.pk"),
    ("Airblue", "Travel & hospitality", "Islamabad", "airblue.com"),
    ("Serene Air", "Travel & hospitality", "Islamabad", "sereneair.com"),
    ("AirSial", "Travel & hospitality", "Sialkot", "airsial.com"),
    ("Fly Jinnah", "Travel & hospitality", "Karachi", "flyjinnah.com"),
    ("Gerry's International", "Travel & hospitality", "Karachi", "gerrys.com.pk"),
    ("Serena Hotels", "Travel & hospitality", "Islamabad", "serenahotels.com"),
    ("Pearl Continental / Hashoo Group", "Travel & hospitality", "Karachi", "pchotels.com"),
    ("Avari Hotels", "Travel & hospitality", "Karachi", "avari.com"),
    ("Mövenpick Hotel Karachi", "Travel & hospitality", "Karachi", "movenpick.com"),
    ("Nishat Hotels (The Nishat)", "Travel & hospitality", "Lahore", "nishathotels.com"),
    ("Daewoo Express", "Travel & hospitality", "Lahore", "daewoo.com.pk"),
    ("Faisal Movers", "Travel & hospitality", "Lahore", "faisalmovers.com"),
    ("Skyways", "Travel & hospitality", "Lahore", ""),

    # ---- Real estate & construction ----
    ("Bahria Town", "Real estate & construction", "Rawalpindi", "bahriatown.com"),
    ("DHA Lahore", "Real estate & construction", "Lahore", "dhalahore.org"),
    ("Emaar Pakistan", "Real estate & construction", "Karachi", "emaar.com"),
    ("Habib Construction Services", "Real estate & construction", "Lahore", "hcs.com.pk"),
    ("Izhar Group", "Real estate & construction", "Lahore", "izhar.com"),
    ("Imarat Group", "Real estate & construction", "Islamabad", "imarat.com.pk"),
    ("Agency21", "Real estate & construction", "Islamabad", "agency21.com.pk"),
    ("Giga Group", "Real estate & construction", "Islamabad", ""),
    ("Zameen Developments", "Real estate & construction", "Lahore", ""),
    ("Frontier Works Organization (FWO)", "Real estate & construction", "Rawalpindi", "fwo.com.pk"),
    ("National Logistics Corporation (NLC)", "Real estate & construction", "Rawalpindi", "nlc.com.pk"),

    # ---- BPO & CX ----
    ("ibex Pakistan", "BPO & CX", "Karachi", "ibex.co"),
    ("TRG Pakistan", "BPO & CX", "Karachi", "trgworld.com"),
    ("Mindbridge", "BPO & CX", "Lahore", "mindbridge.com.pk"),
    ("Touchstone Communications", "BPO & CX", "Islamabad", "touchstonecom.com"),
    ("Ovex BPO", "BPO & CX", "Islamabad", ""),
    ("Abacus Outsourcing", "BPO & CX", "Lahore", ""),

    # ---- HR & talent ----
    ("Rozee.pk (Naseeb Networks)", "HR & talent", "Lahore", "rozee.pk"),
    ("Mustakbil", "HR & talent", "Lahore", "mustakbil.com"),
    ("BrightSpyre", "HR & talent", "Islamabad", "brightspyre.com"),
    ("HRSG", "HR & talent", "Karachi", "hrsg.com.pk"),
    ("People (HR Solutions)", "HR & talent", "Karachi", "people.com.pk"),

    # ---- Consulting & professional ----
    ("A.F. Ferguson (PwC Pakistan)", "Consulting & professional", "Karachi", "pwc.com.pk"),
    ("KPMG Taseer Hadi", "Consulting & professional", "Karachi", "kpmg.com.pk"),
    ("EY Ford Rhodes", "Consulting & professional", "Karachi", "ey.com"),
    ("Deloitte Yousuf Adil", "Consulting & professional", "Karachi", "deloitte.com"),
    ("Grant Thornton Anjum Rahman", "Consulting & professional", "Karachi", ""),
    ("BDO Pakistan", "Consulting & professional", "Karachi", "bdo.com.pk"),
    ("McKinsey & Company Pakistan", "Consulting & professional", "Karachi", "mckinsey.com"),
    ("BCG Pakistan", "Consulting & professional", "Karachi", "bcg.com"),
    ("Sidat Hyder Morshed Associates", "Consulting & professional", "Karachi", "sidathyder.com.pk"),

    # ---- Defense & aerospace ----
    ("Pakistan Aeronautical Complex (PAC Kamra)", "Defense & aerospace", "Kamra", "pac.org.pk"),
    ("Pakistan Ordnance Factories (POF)", "Defense & aerospace", "Wah", "pof.gov.pk"),
    ("Heavy Industries Taxila (HIT)", "Defense & aerospace", "Taxila", "hit.gov.pk"),
    ("NESCOM", "Defense & aerospace", "Islamabad", ""),
    ("SUPARCO", "Defense & aerospace", "Karachi", "suparco.gov.pk"),
    ("GIDS", "Defense & aerospace", "Rawalpindi", "gids.com.pk"),
    ("CARE Pvt Ltd", "Defense & aerospace", "Islamabad", ""),
    ("Integrated Dynamics", "Defense & aerospace", "Karachi", "idaerospace.com"),
    ("Satuma", "Defense & aerospace", "Islamabad", "satuma.com.pk"),
    ("East West Infiniti", "Defense & aerospace", "Karachi", "ewi.com.pk"),
    ("Shibli Electronics", "Defense & aerospace", "Islamabad", ""),

    # ---- Agriculture ----
    ("Syngenta Pakistan", "Agriculture", "Karachi", "syngenta.com.pk"),
    ("FMC Pakistan", "Agriculture", "Lahore", ""),
    ("Corteva Agriscience Pakistan", "Agriculture", "Lahore", "corteva.com.pk"),
    ("Four Brothers Group", "Agriculture", "Lahore", "fourb.com.pk"),
    ("Guard Agricultural Research", "Agriculture", "Lahore", "guardagri.com"),
    ("Jaffer Brothers", "Agriculture", "Karachi", "jaffer.com"),
    ("Sapphire Dairies", "Agriculture", "Lahore", ""),

    # ---- NGO & development ----
    ("Akhuwat Foundation", "NGO & development", "Lahore", "akhuwat.org.pk"),
    ("Edhi Foundation", "NGO & development", "Karachi", "edhi.org"),
    ("Saylani Welfare Trust", "NGO & development", "Karachi", "saylaniwelfare.com"),
    ("Alkhidmat Foundation", "NGO & development", "Lahore", "alkhidmat.org"),
    ("The Citizens Foundation (TCF)", "NGO & development", "Karachi", "tcf.org.pk"),
    ("HANDS Pakistan", "NGO & development", "Karachi", "hands.org.pk"),
    ("Chhipa Welfare", "NGO & development", "Karachi", "chhipa.org"),
    ("WWF-Pakistan", "NGO & development", "Lahore", "wwfpak.org"),
    ("UNDP Pakistan", "NGO & development", "Islamabad", "undp.org"),
    ("UNICEF Pakistan", "NGO & development", "Islamabad", "unicef.org"),
    ("WHO Pakistan", "NGO & development", "Islamabad", "who.int"),
    ("World Bank Pakistan", "NGO & development", "Islamabad", "worldbank.org"),
    ("Asian Development Bank Pakistan", "NGO & development", "Islamabad", "adb.org"),
    ("British Council Pakistan", "NGO & development", "Islamabad", "britishcouncil.pk"),
    ("Aga Khan Foundation Pakistan", "NGO & development", "Islamabad", "akdn.org"),
    ("Kashf Foundation", "NGO & development", "Lahore", "kashf.org"),
    ("NRSP", "NGO & development", "Islamabad", "nrsp.org.pk"),

    # ---- Government & public sector ----
    ("NADRA", "Government & public sector", "Islamabad", "nadra.gov.pk"),
    ("NADRA Technologies (NTL)", "Government & public sector", "Islamabad", ""),
    ("Punjab Information Technology Board (PITB)", "Government & public sector", "Lahore", "pitb.gov.pk"),
    ("KP IT Board (KPITB)", "Government & public sector", "Peshawar", "kpitb.gov.pk"),
    ("National IT Board (NITB)", "Government & public sector", "Islamabad", "nitb.gov.pk"),
    ("Pakistan Software Export Board (PSEB)", "Government & public sector", "Islamabad", "pseb.org.pk"),
    ("Ignite National Technology Fund", "Government & public sector", "Islamabad", "ignite.org.pk"),
    ("PRAL", "Government & public sector", "Islamabad", "pral.com.pk"),
    ("SECP", "Government & public sector", "Islamabad", "secp.gov.pk"),
    ("PTA", "Government & public sector", "Islamabad", "pta.gov.pk"),
    ("FBR", "Government & public sector", "Islamabad", "fbr.gov.pk"),
    ("Pakistan Railways", "Government & public sector", "Lahore", "pakrail.gov.pk"),
    ("National Highway Authority (NHA)", "Government & public sector", "Islamabad", "nha.gov.pk"),
    ("PAEC", "Government & public sector", "Islamabad", "paec.gov.pk"),
    ("Civil Aviation Authority (CAA)", "Government & public sector", "Karachi", "caapakistan.com.pk"),
    ("Punjab Safe Cities Authority (PSCA)", "Government & public sector", "Lahore", "psca.gop.pk"),
    ("The Urban Unit", "Government & public sector", "Lahore", "urbanunit.gov.pk"),
    ("NIC Lahore", "Government & public sector", "Lahore", "niclahore.com"),
    ("NIC Islamabad", "Government & public sector", "Islamabad", "nicislamabad.com"),
    ("NIC Karachi", "Government & public sector", "Karachi", "nickarachi.com"),
    ("Plan9 (PITB incubator)", "Government & public sector", "Lahore", "plan9.pitb.gov.pk"),

    # ---- Startups & VC ----
    ("Katalyst Labs", "Startups & VC", "Karachi", "katalystlabs.pk"),
    ("Invest2Innovate (i2i)", "Startups & VC", "Islamabad", "invest2innovate.com"),
    ("Fatima Gobi Ventures", "Startups & VC", "Lahore", ""),
    ("Sarmayacar", "Startups & VC", "Karachi", "sarmayacar.com"),
    ("Indus Valley Capital", "Startups & VC", "Karachi", "indusvalley.vc"),
    ("Zayn VC", "Startups & VC", "Karachi", "zayn.vc"),
    ("47 Ventures", "Startups & VC", "Lahore", ""),
    ("Lakson Investments", "Startups & VC", "Karachi", "laksoninvestments.com"),
    ("TPL Trakker", "Startups & VC", "Karachi", "tpltrakker.com"),
    ("TPL Properties", "Startups & VC", "Karachi", "tplproperty.com"),
]

# Remove any placeholder rows that slipped in during editing.
PK_DIRECTORY = [r for r in PK_DIRECTORY if r[1] != "REMOVE"]
